-- ============================================================
-- Nobre Amor Baby — atomic Asaas webhook application + verified paid amounts
-- Run after migration_016_payment_attempt_serialization.sql.
-- ============================================================

alter table public.payment_attempts
  add column if not exists provider_reported_state text,
  add column if not exists provider_amount_cents bigint,
  add column if not exists amount_verification_state text not null default 'not_applicable';

alter table public.payment_attempts
  drop constraint if exists payment_attempts_state_check;

alter table public.payment_attempts
  add constraint payment_attempts_state_check
  check (
    state in (
      'claimed',
      'provider_uncertain',
      'pending',
      'paid',
      'payment_review',
      'failed',
      'expired',
      'cancelled',
      'refunded'
    )
  );

alter table public.payment_attempts
  drop constraint if exists payment_attempts_amount_verification_check;

alter table public.payment_attempts
  add constraint payment_attempts_amount_verification_check
  check (
    amount_verification_state in (
      'not_applicable',
      'verified',
      'mismatch',
      'invalid',
      'legacy_unverified'
    )
  );

-- Never guess whether an already-paid historical ledger row was amount-verified.
-- Active paid ownership is verifiable only when the order's durable paid total
-- exactly equals its authoritative total. Preserve every other historical provider-
-- reported paid record for investigation, but remove it from verified-paid ownership
-- until a later provider event supplies an amount that passes validation.
update public.payment_attempts pa
set
  provider_reported_state = coalesce(pa.provider_reported_state, 'paid'),
  provider_amount_cents = coalesce(pa.provider_amount_cents, o.paid_total_cents),
  amount_verification_state = 'verified'
from public.orders o
where pa.state = 'paid'
  and o.active_payment_attempt_id = pa.id
  and o.payment_state = 'paid'
  and o.paid_total_cents is not null
  and o.paid_total_cents = o.total_cents;

update public.payment_attempts pa
set
  provider_reported_state = coalesce(pa.provider_reported_state, 'paid'),
  state = 'payment_review',
  amount_verification_state = 'legacy_unverified',
  updated_at = now()
where pa.state = 'paid'
  and pa.amount_verification_state <> 'verified';

alter table public.payment_attempts
  drop constraint if exists payment_attempts_paid_requires_verified_amount;

alter table public.payment_attempts
  add constraint payment_attempts_paid_requires_verified_amount
  check (state <> 'paid' or amount_verification_state = 'verified');

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  order_id uuid not null references public.orders(id) on delete cascade,
  payment_attempt_id uuid not null references public.payment_attempts(id) on delete cascade,
  provider_payment_id text,
  proposed_state text not null,
  provider_amount_cents bigint,
  result text not null,
  error_code text,
  received_at timestamptz not null default now(),
  applied_at timestamptz not null default now(),

  constraint payment_webhook_events_provider_event_unique unique (provider, event_id),
  constraint payment_webhook_events_result_check check (
    result in (
      'applied',
      'additional_paid',
      'switch_to_paid',
      'ignored_stale',
      'ignored_non_owner',
      'rejected_amount'
    )
  )
);

create index if not exists idx_payment_webhook_events_attempt
  on public.payment_webhook_events(payment_attempt_id, applied_at desc);

alter table public.payment_webhook_events enable row level security;
revoke all on table public.payment_webhook_events from anon, authenticated;

create or replace function public.apply_asaas_payment_webhook(
  p_order_id uuid,
  p_payment_attempt_id uuid,
  p_event_id text,
  p_provider_payment_id text,
  p_proposed_state text,
  p_provider_amount_cents bigint,
  p_provider_amount_valid boolean,
  p_payment_method text,
  p_payment_link_url text,
  p_payment_expires_at timestamptz,
  p_paid_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_order public.orders%rowtype;
  v_attempt public.payment_attempts%rowtype;
  v_existing_event public.payment_webhook_events%rowtype;
  v_fallback public.payment_attempts%rowtype;
  v_attempt_next_state text;
  v_order_next_state text;
  v_amount_error text;
  v_result text := 'applied';
  v_owns_order boolean := false;
begin
  if p_event_id is null or btrim(p_event_id) = '' then
    raise exception using errcode = '22023', message = 'webhook_event_id_required';
  end if;

  if p_proposed_state is null or p_proposed_state not in (
    'pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded'
  ) then
    raise exception using errcode = '22023', message = 'invalid_payment_state';
  end if;

  select *
  into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'order_not_found';
  end if;

  select *
  into v_attempt
  from public.payment_attempts
  where id = p_payment_attempt_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'payment_attempt_not_found';
  end if;

  if v_attempt.order_id <> v_order.id then
    raise exception using errcode = '23514', message = 'payment_attempt_order_mismatch';
  end if;

  select *
  into v_existing_event
  from public.payment_webhook_events
  where provider = 'asaas'
    and event_id = p_event_id;

  if found then
    if v_existing_event.order_id <> v_order.id
      or v_existing_event.payment_attempt_id <> v_attempt.id
    then
      raise exception using errcode = '23505', message = 'payment_webhook_event_conflict';
    end if;

    return pg_catalog.jsonb_build_object(
      'result', v_existing_event.result,
      'duplicate', true,
      'error_code', v_existing_event.error_code,
      'order_code', v_order.order_code,
      'payment_state', v_order.payment_state,
      'attempt_state', v_attempt.state,
      'active_payment_attempt_id', v_order.active_payment_attempt_id
    );
  end if;

  if v_attempt.provider_payment_id is not null
    and p_provider_payment_id is not null
    and v_attempt.provider_payment_id <> p_provider_payment_id
  then
    raise exception using errcode = '23505', message = 'payment_reference_conflict';
  end if;

  v_owns_order := (
    v_order.active_payment_attempt_id = v_attempt.id
    or (
      v_order.active_payment_attempt_id is null
      and v_attempt.attempt_kind = 'original'
    )
  );

  if p_proposed_state = 'paid' then
    if not coalesce(p_provider_amount_valid, false) or p_provider_amount_cents is null then
      v_amount_error := 'payment_amount_invalid';
    elsif p_provider_amount_cents <> v_order.total_cents then
      v_amount_error := 'payment_amount_mismatch';
    end if;

    if v_amount_error is not null then
      update public.payment_attempts
      set
        provider_payment_id = coalesce(provider_payment_id, p_provider_payment_id),
        provider_reported_state = 'paid',
        provider_amount_cents = case
          when v_attempt.state = 'paid' and v_attempt.amount_verification_state = 'verified'
            then v_attempt.provider_amount_cents
          when v_attempt.state in ('refunded', 'cancelled')
            then v_attempt.provider_amount_cents
          else p_provider_amount_cents
        end,
        amount_verification_state = case
          when v_attempt.state = 'paid' and v_attempt.amount_verification_state = 'verified'
            then v_attempt.amount_verification_state
          when v_attempt.state in ('refunded', 'cancelled')
            then v_attempt.amount_verification_state
          when v_amount_error = 'payment_amount_mismatch' then 'mismatch'
          else 'invalid'
        end,
        state = case
          when v_attempt.state in ('paid', 'refunded', 'cancelled') then v_attempt.state
          else 'payment_review'
        end,
        updated_at = now()
      where id = v_attempt.id;

      insert into public.payment_webhook_events (
        provider,
        event_id,
        order_id,
        payment_attempt_id,
        provider_payment_id,
        proposed_state,
        provider_amount_cents,
        result,
        error_code
      ) values (
        'asaas',
        p_event_id,
        v_order.id,
        v_attempt.id,
        p_provider_payment_id,
        p_proposed_state,
        p_provider_amount_cents,
        'rejected_amount',
        v_amount_error
      );

      return pg_catalog.jsonb_build_object(
        'result', 'rejected_amount',
        'duplicate', false,
        'error_code', v_amount_error,
        'order_code', v_order.order_code,
        'payment_state', v_order.payment_state,
        'attempt_state', case
          when v_attempt.state in ('paid', 'refunded', 'cancelled') then v_attempt.state
          else 'payment_review'
        end,
        'active_payment_attempt_id', v_order.active_payment_attempt_id
      );
    end if;
  end if;

  v_attempt_next_state := case v_attempt.state
    when 'pending' then
      case when p_proposed_state in ('pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded')
        then p_proposed_state else v_attempt.state end
    when 'failed' then
      case when p_proposed_state in ('failed', 'paid', 'refunded')
        then p_proposed_state else v_attempt.state end
    when 'expired' then
      case when p_proposed_state in ('expired', 'paid', 'refunded')
        then p_proposed_state else v_attempt.state end
    when 'paid' then
      case when p_proposed_state in ('paid', 'refunded')
        then p_proposed_state else v_attempt.state end
    when 'refunded' then 'refunded'
    when 'cancelled' then 'cancelled'
    when 'payment_review' then
      case when p_proposed_state in ('paid', 'refunded', 'failed', 'expired', 'cancelled')
        then p_proposed_state else v_attempt.state end
    else p_proposed_state
  end;

  if v_attempt_next_state <> p_proposed_state then
    update public.payment_attempts
    set
      provider_payment_id = coalesce(provider_payment_id, p_provider_payment_id),
      provider_reported_state = p_proposed_state,
      updated_at = now()
    where id = v_attempt.id;

    insert into public.payment_webhook_events (
      provider,
      event_id,
      order_id,
      payment_attempt_id,
      provider_payment_id,
      proposed_state,
      provider_amount_cents,
      result,
      error_code
    ) values (
      'asaas',
      p_event_id,
      v_order.id,
      v_attempt.id,
      p_provider_payment_id,
      p_proposed_state,
      p_provider_amount_cents,
      'ignored_stale',
      null
    );

    return pg_catalog.jsonb_build_object(
      'result', 'ignored_stale',
      'duplicate', false,
      'error_code', null,
      'order_code', v_order.order_code,
      'payment_state', v_order.payment_state,
      'attempt_state', v_attempt.state,
      'active_payment_attempt_id', v_order.active_payment_attempt_id
    );
  end if;

  update public.payment_attempts
  set
    provider_payment_id = coalesce(provider_payment_id, p_provider_payment_id),
    provider_reported_state = p_proposed_state,
    provider_amount_cents = case
      when p_proposed_state = 'paid' then p_provider_amount_cents
      else provider_amount_cents
    end,
    amount_verification_state = case
      when p_proposed_state = 'paid' then 'verified'
      else amount_verification_state
    end,
    state = v_attempt_next_state,
    last_event_id = p_event_id,
    updated_at = now()
  where id = v_attempt.id;

  if p_proposed_state = 'paid'
    and v_order.payment_state = 'paid'
    and v_order.active_payment_attempt_id is distinct from v_attempt.id
    and v_order.payment_external_id is not null
    and p_provider_payment_id is not null
    and v_order.payment_external_id <> p_provider_payment_id
  then
    v_result := 'additional_paid';
  elsif p_proposed_state = 'refunded' and v_owns_order then
    select *
    into v_fallback
    from public.payment_attempts
    where order_id = v_order.id
      and id <> v_attempt.id
      and state = 'paid'
      and amount_verification_state = 'verified'
    order by created_at asc, id asc
    limit 1
    for update;

    if found then
      update public.orders
      set
        payment_provider = 'asaas',
        payment_method = coalesce(v_fallback.payment_method, payment_method),
        payment_ref = coalesce(v_fallback.provider_payment_id, payment_ref),
        payment_state = 'paid',
        payment_external_id = coalesce(v_fallback.provider_payment_id, payment_external_id),
        active_payment_attempt_id = v_fallback.id,
        payment_last_event = p_event_id
      where id = v_order.id;
      v_result := 'switch_to_paid';
    else
      update public.orders
      set
        payment_provider = 'asaas',
        payment_method = coalesce(p_payment_method, payment_method),
        payment_ref = coalesce(p_provider_payment_id, payment_ref),
        payment_state = 'refunded',
        payment_external_id = coalesce(p_provider_payment_id, payment_external_id),
        active_payment_attempt_id = v_attempt.id,
        payment_last_event = p_event_id
      where id = v_order.id;
      v_result := 'applied';
    end if;
  elsif not v_owns_order and p_proposed_state <> 'paid' then
    v_result := 'ignored_non_owner';
  elsif p_proposed_state = 'paid' then
    v_order_next_state := case v_order.payment_state
      when 'pending' then 'paid'
      when 'failed' then 'paid'
      when 'expired' then 'paid'
      when 'paid' then 'paid'
      when 'refunded' then 'refunded'
      when 'cancelled' then 'cancelled'
      else 'paid'
    end;

    if v_order_next_state = 'paid' then
      update public.orders
      set
        payment_provider = 'asaas',
        payment_method = coalesce(p_payment_method, payment_method),
        payment_ref = coalesce(p_provider_payment_id, payment_ref),
        payment_state = 'paid',
        payment_external_id = coalesce(p_provider_payment_id, payment_external_id),
        payment_link_url = coalesce(p_payment_link_url, payment_link_url),
        payment_expires_at = coalesce(p_payment_expires_at, payment_expires_at),
        active_payment_attempt_id = v_attempt.id,
        payment_last_event = p_event_id,
        paid_at = coalesce(paid_at, p_paid_at, now()),
        paid_total_cents = p_provider_amount_cents
      where id = v_order.id;
      v_result := 'applied';
    else
      v_result := 'ignored_stale';
    end if;
  elsif v_owns_order then
    v_order_next_state := case v_order.payment_state
      when 'pending' then
        case when p_proposed_state in ('pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded')
          then p_proposed_state else v_order.payment_state end
      when 'failed' then
        case when p_proposed_state in ('failed', 'paid', 'refunded')
          then p_proposed_state else v_order.payment_state end
      when 'expired' then
        case when p_proposed_state in ('expired', 'paid', 'refunded')
          then p_proposed_state else v_order.payment_state end
      when 'paid' then
        case when p_proposed_state in ('paid', 'refunded')
          then p_proposed_state else v_order.payment_state end
      when 'refunded' then 'refunded'
      when 'cancelled' then 'cancelled'
      else p_proposed_state
    end;

    if v_order_next_state = p_proposed_state then
      update public.orders
      set
        payment_provider = 'asaas',
        payment_method = coalesce(p_payment_method, payment_method),
        payment_ref = coalesce(p_provider_payment_id, payment_ref),
        payment_state = v_order_next_state,
        payment_external_id = coalesce(p_provider_payment_id, payment_external_id),
        payment_link_url = coalesce(p_payment_link_url, payment_link_url),
        payment_expires_at = coalesce(p_payment_expires_at, payment_expires_at),
        active_payment_attempt_id = v_attempt.id,
        payment_last_event = p_event_id
      where id = v_order.id;
      v_result := 'applied';
    else
      v_result := 'ignored_stale';
    end if;
  end if;

  insert into public.payment_webhook_events (
    provider,
    event_id,
    order_id,
    payment_attempt_id,
    provider_payment_id,
    proposed_state,
    provider_amount_cents,
    result,
    error_code
  ) values (
    'asaas',
    p_event_id,
    v_order.id,
    v_attempt.id,
    p_provider_payment_id,
    p_proposed_state,
    p_provider_amount_cents,
    v_result,
    null
  );

  select * into v_order from public.orders where id = p_order_id;
  select * into v_attempt from public.payment_attempts where id = p_payment_attempt_id;

  return pg_catalog.jsonb_build_object(
    'result', v_result,
    'duplicate', false,
    'error_code', null,
    'order_code', v_order.order_code,
    'payment_state', v_order.payment_state,
    'attempt_state', v_attempt.state,
    'active_payment_attempt_id', v_order.active_payment_attempt_id,
    'provider_payment_id', v_attempt.provider_payment_id
  );
exception
  when unique_violation then
    -- Provider-payment uniqueness and event uniqueness are both financial identity
    -- constraints. A concurrent duplicate event normally serializes on the locked
    -- order row and is handled above; any other uniqueness collision must abort the
    -- entire transaction so the provider can retry after the conflict is resolved.
    raise;
end;
$$;

revoke all on function public.apply_asaas_payment_webhook(
  uuid, uuid, text, text, text, bigint, boolean, text, text, timestamptz, timestamptz
) from public;
revoke execute on function public.apply_asaas_payment_webhook(
  uuid, uuid, text, text, text, bigint, boolean, text, text, timestamptz, timestamptz
) from anon;
revoke execute on function public.apply_asaas_payment_webhook(
  uuid, uuid, text, text, text, bigint, boolean, text, text, timestamptz, timestamptz
) from authenticated;
grant execute on function public.apply_asaas_payment_webhook(
  uuid, uuid, text, text, text, bigint, boolean, text, text, timestamptz, timestamptz
) to service_role;

-- Preserve backend-only ledger access semantics.
alter table public.payment_attempts enable row level security;
