  /**
 * Seed products — client-side fallback data for when the DB is
 * not configured or returns an empty list.
 *
 * IDs are deterministic so editing works across renders.
 * collection_id references seed collection IDs where appropriate.
 */

const SEED_PRODUCTS = [
  {
    id: 'seed-prod-001',
    name: 'Macacão Algodão Listrado',
    slug: 'macacao-algodao-listrado',
    description: 'Macacão de algodão orgânico com listras delicadas. Botões de pressão para facilitar a troca.',
    price_cents: 8990,
    old_price_cents: 11990,
    tag: 'Mais Vendido',
    featured: true,
    is_public: true,
    in_stock: true,
    stock_count: 24,
    size_group: 'roupa',
    size_options: ['0-1m', '1-3m', '3-6m', '6-9m'],
    age_min_months: 0,
    age_max_months: 9,
    category_slug: 'roupas',
    collection_id: 'seed-coll-002',
    image_urls: ['https://placehold.co/600x600/F0DAE8/373438?text=Macac%C3%A3o'],
    weight_grams: 180,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'seed-prod-002',
    name: 'Vestido Festa Rosa',
    slug: 'vestido-festa-rosa',
    description: 'Vestido de tule com laço de cetim. Perfeito para batizados e festas.',
    price_cents: 14990,
    old_price_cents: null,
    tag: 'Novo',
    featured: true,
    is_public: true,
    in_stock: true,
    stock_count: 12,
    size_group: 'roupa',
    size_options: ['3-6m', '6-9m', '9-12m', '1 ano', '2 anos'],
    age_min_months: 3,
    age_max_months: 24,
    category_slug: 'roupas',
    collection_id: 'seed-coll-003',
    image_urls: ['https://placehold.co/600x600/FDF8FB/A49AAE?text=Vestido+Festa'],
    weight_grams: 220,
    created_at: '2026-02-08T10:00:00Z',
  },
  {
    id: 'seed-prod-003',
    name: 'Kit Body Manga Curta (3 peças)',
    slug: 'kit-body-manga-curta',
    description: 'Kit com 3 bodies de manga curta em algodão suave. Cores sortidas.',
    price_cents: 6490,
    old_price_cents: 7990,
    tag: 'Promoção',
    featured: false,
    is_public: true,
    in_stock: true,
    stock_count: 40,
    size_group: 'roupa',
    size_options: ['RN', 'P', 'M', 'G'],
    age_min_months: 0,
    age_max_months: 12,
    category_slug: 'roupas',
    collection_id: 'seed-coll-001',
    image_urls: ['https://placehold.co/600x600/A49AAE/FDF8FB?text=Kit+Body'],
    weight_grams: 250,
    created_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'seed-prod-004',
    name: 'Sapatinho Tricô Marinho',
    slug: 'sapatinho-trico-marinho',
    description: 'Sapatinho de tricô feito à mão, macio e quentinho. Ideal para todas as estações.',
    price_cents: 3990,
    old_price_cents: null,
    tag: '',
    featured: false,
    is_public: true,
    in_stock: true,
    stock_count: 18,
    size_group: 'calçado',
    size_options: ['13', '14', '15', '16'],
    age_min_months: 0,
    age_max_months: 12,
    category_slug: 'calcados',
    collection_id: 'seed-coll-004',
    image_urls: ['https://placehold.co/600x600/373438/F0DAE8?text=Sapatinho'],
    weight_grams: 80,
    created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'seed-prod-005',
    name: 'Tiara Laço de Cetim',
    slug: 'tiara-laco-cetim',
    description: 'Tiara delicada com laço de cetim. Elástico extra macio. Tamanho único.',
    price_cents: 2490,
    old_price_cents: null,
    tag: '',
    featured: false,
    is_public: true,
    in_stock: true,
    stock_count: 35,
    size_group: 'acessório',
    size_options: ['Único'],
    age_min_months: 0,
    age_max_months: 36,
    category_slug: 'acessorios',
    collection_id: 'seed-coll-005',
    image_urls: ['https://placehold.co/600x600/F0DAE8/A49AAE?text=Tiara'],
    weight_grams: 30,
    created_at: '2026-01-28T10:00:00Z',
  },
  {
    id: 'seed-prod-006',
    name: 'Casaquinho Plush Urso',
    slug: 'casaquinho-plush-urso',
    description: 'Casaquinho em plush com capuz de ursinho. Forro em algodão.',
    price_cents: 12990,
    old_price_cents: 15990,
    tag: 'Inverno',
    featured: true,
    is_public: true,
    in_stock: false,
    stock_count: 0,
    size_group: 'roupa',
    size_options: ['3-6m', '6-9m', '9-12m', '12-18m'],
    age_min_months: 3,
    age_max_months: 18,
    category_slug: 'roupas',
    collection_id: 'seed-coll-004',
    image_urls: ['https://placehold.co/600x600/FDF8FB/373438?text=Casaquinho'],
    weight_grams: 300,
    created_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'seed-prod-007',
    name: 'Conjunto Shorts + Camiseta Tropical',
    slug: 'conjunto-shorts-camiseta-tropical',
    description: 'Conjunto de verão com estampa tropical. Tecido leve e fresquinho.',
    price_cents: 7490,
    old_price_cents: null,
    tag: 'Verão',
    featured: false,
    is_public: false,
    in_stock: true,
    stock_count: 15,
    size_group: 'roupa',
    size_options: ['6-9m', '9-12m', '1 ano', '2 anos', '3 anos'],
    age_min_months: 6,
    age_max_months: 36,
    category_slug: 'roupas',
    collection_id: 'seed-coll-001',
    image_urls: ['https://placehold.co/600x600/A49AAE/373438?text=Conjunto+Tropical'],
    weight_grams: 150,
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'seed-prod-008',
    name: 'Manta de Algodão Estrelas',
    slug: 'manta-algodao-estrelas',
    description: 'Manta macia em algodão com estampa de estrelinhas. 80×100 cm.',
    price_cents: 5990,
    old_price_cents: 6990,
    tag: '',
    featured: false,
    is_public: true,
    in_stock: true,
    stock_count: 22,
    size_group: 'acessório',
    size_options: ['Único'],
    age_min_months: 0,
    age_max_months: 36,
    category_slug: 'enxoval',
    collection_id: 'seed-coll-002',
    image_urls: ['https://placehold.co/600x600/373438/A49AAE?text=Manta+Estrelas'],
    weight_grams: 350,
    created_at: '2026-01-15T10:00:00Z',
  },
];

/**
 * Returns a deep copy of seeded products so callers can
 * safely mutate local state without affecting the constant.
 */
export function getSeededProducts() {
  return SEED_PRODUCTS.map((p) => ({ ...p, size_options: [...p.size_options] }));
}
